spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:competition_system;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=USER
    username: sa
    password:
